name: Run tests

on:
  push:
  pull_request:
    branches:
      - main
env:
  NODE_API_KEY: 'https://eth-mainnet.alchemyapi.io/v2/_FhcEg_5DvMaewwIWP-3ZsH7HuwejLTP'
  MNEMONIC: '0x76e84d048ab2f7e50865817dda3eef706aaeeeb592c1e0a2d677e914bda4e9d6'
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test

  TypeScript-Static-Analyis:
    runs-on: ubuntu-latest
    name: TypeScript static analysis
    needs: Unit-Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint-ts

  Solidity-Static-Analysis-Solhint:
    runs-on: ubuntu-latest
    name: Solidity static analysis (Solhint)
    needs: Unit-Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint-sol


  Solidity-Static-Analysis-Slither:
    runs-on: ubuntu-latest
    name: Solidity static analysis (Slither)
    needs: Unit-Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Slither Static Analysis
        run: slither . --config-file slither.json
